<header class="title-bar clearfix">
	<div class="wrapper">
		<img amp-img-id="AMP_3" alt="navigation" role="button" class="amp-sidebar-headopen" on="tap:sidebar.open" src="http://ampbyexample.com/img/ic_menu_white_2x_web_24dp.png">
		<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /> ⚡ AMP</a>
	</div>
</header>


<amp-sidebar id='sidebar'
layout="nodisplay"
side="left">
	<amp-img class='amp-close-image'
	src="http://ampbyexample.com/img/ic_chevron_left_black_24dp_2x.png"
	width="20"
	height="20"
	alt="close sidebar"
	on="tap:sidebar.close"
	role="button"
	tabindex="0"></amp-img>
	<ul class="sidebar-links">
		<li>
			<a href="/mens">Mens</a>
		</li>
		<li>
			<a href="/womens">Womens</a>
		</li>
		<li>
			<a href="/cart">Cart</a>
		</li>
	</ul>
</amp-sidebar>