<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>
<script async custom-element="amp-install-serviceworker" src="https://cdn.ampproject.org/v0/amp-install-serviceworker-0.1.js"></script>
<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
<script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
<script async custom-element="amp-fit-text" src="https://cdn.ampproject.org/v0/amp-fit-text-0.1.js"></script> 
<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700' rel='stylesheet' type='text/css'>
<amp-analytics type="googleanalytics"></amp-analytics>

<style amp-custom>
html {
	font-family: Helvetica, Arial, sans-serif;
}
h1, h2, h3, h4, h5, h6 {
    margin-top: 24px;
    margin-bottom: 16px;
    font-family: Roboto,Helvetica,Arial,sans-serif;
}
header.title-bar {
	background: #232f3e;
	border-bottom: 0;
	padding: 0.5em;
	box-shadow: 0 0 24px 0 rgba(0, 0, 0, 0.46);
	position: relative;
	z-index: 30;
	vertical-align:middle;
}

.amp-sidebar-headopen {
	vertical-align:middle;
	width: 30px;
    margin-right: 20px;
    margin-left: 15px;
}

.sidebar-links {
	padding: 0;
	margin: 0;
	list-style: none;
}

.sidebar-links a {
    display: block;
    font-weight: 500;
    padding-left: 16px;
    color: rgba(0,0,0,.87);
    line-height: 40px;
    font-family: Roboto,Helvetica,Arial,sans-serif;
    text-decoration: none;
    font-size: 13px;
}

header .logo {
	display: inline-block;
	text-decoration: none;
}

header .logo img {
	-webkit-filter:invert(100%);
	width: 40px;
	vertical-align:middle;
}

amp-sidebar {
	background: white;
	box-shadow: 0 0 24px 0 rgba(0, 0, 0, 0.46);
}
.-amp-sidebar-mask {
	opacity: 0.4;
  -webkit-filter: blur(5px);
  -moz-filter: blur(5px);
  -o-filter: blur(5px);
  -ms-filter: blur(5px);
  filter: blur(5px);

}
</style>

<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
